import { describe, it, expect } from 'vitest';
import {
  generateMarkdownReport,
  generateJsonReport,
  generateHtmlReport,
  buildReportData,
} from '../index.js';
import type {
  ReportData,
  ReportFileResult,
  JsonReportOutput,
} from '../index.js';

// ─────────────────────────────────────────────────────────────────────────────
// Test Fixtures
// ─────────────────────────────────────────────────────────────────────────────

function createTestReportData(overrides: Partial<ReportData> = {}): ReportData {
  return {
    generatedAt: '2026-02-08T12:00:00.000Z',
    verdict: 'WARN',
    score: 0.71,
    repository: {
      repository: 'github.com/acme/api',
      branch: 'feature/add-payments',
      commit: 'abc1234',
    },
    coverage: {
      totalFiles: 15,
      specCoveredFiles: 10,
      coveragePercent: 67,
      passingFiles: 12,
      warningFiles: 2,
      failingFiles: 1,
    },
    files: [
      {
        file: 'src/auth/login.ts',
        status: 'PASS',
        method: 'ISL verified',
        score: 0.95,
        specFile: 'src/auth/login.isl',
        blockers: [],
      },
      {
        file: 'src/payments/checkout.ts',
        status: 'WARN',
        method: 'Specless',
        score: 0.55,
        blockers: ['No ISL spec found'],
      },
      {
        file: 'src/payments/refund.ts',
        status: 'FAIL',
        method: 'Fake feature',
        score: 0.23,
        blockers: ['Fake feature detected'],
        finding: 'processRefund() never calls payment gateway',
        recommendation: 'Create an ISL spec and implement actual refund logic',
      },
    ],
    mode: 'mixed',
    duration: 1234,
    blockers: ['src/payments/refund.ts: Fake feature detected'],
    recommendations: [
      { priority: 1, text: 'Generate ISL specs for src/payments/', target: 'src/payments/' },
      { priority: 2, text: 'Update src/auth/login.isl — spec is 30 days older than code', target: 'src/auth/login.isl' },
      { priority: 3, text: 'Add rate limiting to POST /api/admin/users' },
    ],
    ...overrides,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Markdown Report Tests
// ─────────────────────────────────────────────────────────────────────────────

describe('generateMarkdownReport', () => {
  it('should produce valid markdown with all sections', () => {
    const data = createTestReportData();
    const md = generateMarkdownReport(data, 'full');

    // Header
    expect(md).toContain('# ShipGate Verification Report');
    expect(md).toContain('**Repository:** github.com/acme/api');
    expect(md).toContain('**Branch:** feature/add-payments');
    expect(md).toContain('**Commit:** `abc1234`');
    expect(md).toContain('**Date:** 2026-02-08');
    expect(md).toContain('WARN');
    expect(md).toContain('Score: 71');

    // Summary table
    expect(md).toContain('## Summary');
    expect(md).toContain('| Files Verified | 15 |');
    expect(md).toContain('| ISL Coverage | 67% (10/15) |');
    expect(md).toContain('| Passing | 12 |');
    expect(md).toContain('| Warnings | 2 |');
    expect(md).toContain('| Failures | 1 |');

    // Failures section
    expect(md).toContain('## Failures');
    expect(md).toContain('`src/payments/refund.ts`');
    expect(md).toContain('Score: 23');

    // Warnings section
    expect(md).toContain('## Warnings');
    expect(md).toContain('`src/payments/checkout.ts`');

    // Passing section
    expect(md).toContain('## Passing');
    expect(md).toContain('`src/auth/login.ts`');

    // Recommendations
    expect(md).toContain('## Recommendations');
    expect(md).toContain('Generate ISL specs for src/payments/');

    // Footer
    expect(md).toContain('Generated by ShipGate');
    expect(md).toContain('Mode: mixed');
  });

  it('should respect failures-only scope', () => {
    const data = createTestReportData();
    const md = generateMarkdownReport(data, 'failures-only');

    expect(md).toContain('## Failures');
    expect(md).not.toContain('## Warnings');
    expect(md).not.toContain('## Passing');
  });

  it('should respect summary scope', () => {
    const data = createTestReportData();
    const md = generateMarkdownReport(data, 'summary');

    expect(md).toContain('## Summary');
    // Failures should still show
    expect(md).toContain('## Failures');
    // Warnings should still show
    expect(md).toContain('## Warnings');
    // Passing should NOT show
    expect(md).not.toContain('## Passing');
  });

  it('should allow custom title', () => {
    const data = createTestReportData();
    const md = generateMarkdownReport(data, 'full', { title: 'My Custom Report' });

    expect(md).toContain('# My Custom Report');
  });

  it('should render SHIP verdict correctly', () => {
    const data = createTestReportData({ verdict: 'SHIP', score: 0.98 });
    const md = generateMarkdownReport(data, 'summary');

    expect(md).toContain('SHIP');
    expect(md).toContain('Score: 98');
  });

  it('should render NO_SHIP verdict correctly', () => {
    const data = createTestReportData({ verdict: 'NO_SHIP', score: 0.23 });
    const md = generateMarkdownReport(data, 'summary');

    expect(md).toContain('NO_SHIP');
    expect(md).toContain('Score: 23');
  });

  it('should include trends when available', () => {
    const data = createTestReportData({
      trends: [
        { date: '2026-02-06T00:00:00Z', coverage: 55, score: 65, label: 'PR #42' },
        { date: '2026-02-07T00:00:00Z', coverage: 60, score: 70, label: 'PR #43' },
        { date: '2026-02-08T00:00:00Z', coverage: 67, score: 71, label: 'PR #44' },
      ],
    });
    const md = generateMarkdownReport(data, 'full', { includeTrends: true });

    expect(md).toContain('## Coverage Trend');
    expect(md).toContain('PR #42');
    expect(md).toContain('PR #44');
  });

  it('should omit recommendations when disabled', () => {
    const data = createTestReportData();
    const md = generateMarkdownReport(data, 'full', { includeRecommendations: false });

    expect(md).not.toContain('## Recommendations');
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// JSON Report Tests
// ─────────────────────────────────────────────────────────────────────────────

describe('generateJsonReport', () => {
  it('should produce valid JSON with schema marker', () => {
    const data = createTestReportData();
    const json = generateJsonReport(data, 'full');
    const parsed: JsonReportOutput = JSON.parse(json);

    expect(parsed.$schema).toBe('shipgate-report-v1');
    expect(parsed.verdict).toBe('WARN');
    expect(parsed.score).toBe(71);
    expect(parsed.repository.url).toBe('github.com/acme/api');
    expect(parsed.repository.branch).toBe('feature/add-payments');
    expect(parsed.coverage.totalFiles).toBe(15);
    expect(parsed.coverage.coveragePercent).toBe(67);
    expect(parsed.mode).toBe('mixed');
    expect(parsed.files).toHaveLength(3);
  });

  it('should filter to failures only in failures-only scope', () => {
    const data = createTestReportData();
    const json = generateJsonReport(data, 'failures-only');
    const parsed: JsonReportOutput = JSON.parse(json);

    expect(parsed.files).toHaveLength(1);
    expect(parsed.files[0]?.status).toBe('FAIL');
  });

  it('should include empty files array in summary scope', () => {
    const data = createTestReportData();
    const json = generateJsonReport(data, 'summary');
    const parsed: JsonReportOutput = JSON.parse(json);

    expect(parsed.files).toHaveLength(0);
    // Coverage/verdict still present
    expect(parsed.coverage.totalFiles).toBe(15);
    expect(parsed.verdict).toBe('WARN');
  });

  it('should convert scores to 0-100 integers', () => {
    const data = createTestReportData();
    const json = generateJsonReport(data, 'full');
    const parsed: JsonReportOutput = JSON.parse(json);

    // Overall score: 0.71 → 71
    expect(parsed.score).toBe(71);
    // File scores
    const authFile = parsed.files.find((f) => f.file === 'src/auth/login.ts');
    expect(authFile?.score).toBe(95);
  });

  it('should include trends when present', () => {
    const data = createTestReportData({
      trends: [
        { date: '2026-02-08T00:00:00Z', coverage: 67, score: 71, label: 'PR #44' },
      ],
    });
    const json = generateJsonReport(data, 'full');
    const parsed: JsonReportOutput = JSON.parse(json);

    expect(parsed.trends).toBeDefined();
    expect(parsed.trends).toHaveLength(1);
    expect(parsed.trends![0]?.label).toBe('PR #44');
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// HTML Report Tests
// ─────────────────────────────────────────────────────────────────────────────

describe('generateHtmlReport', () => {
  it('should produce a valid HTML document', () => {
    const data = createTestReportData();
    const html = generateHtmlReport(data, 'full');

    expect(html).toContain('<!DOCTYPE html>');
    expect(html).toContain('<html lang="en">');
    expect(html).toContain('</html>');
    expect(html).toContain('<title>ShipGate Verification Report</title>');
  });

  it('should contain repository metadata', () => {
    const data = createTestReportData();
    const html = generateHtmlReport(data, 'full');

    expect(html).toContain('github.com/acme/api');
    expect(html).toContain('feature/add-payments');
    expect(html).toContain('abc1234');
  });

  it('should contain summary table', () => {
    const data = createTestReportData();
    const html = generateHtmlReport(data, 'full');

    expect(html).toContain('Files Verified');
    expect(html).toContain('ISL Coverage');
    expect(html).toContain('67%');
    expect(html).toContain('10/15');
  });

  it('should contain failures section', () => {
    const data = createTestReportData();
    const html = generateHtmlReport(data, 'full');

    expect(html).toContain('Failures');
    expect(html).toContain('src/payments/refund.ts');
    expect(html).toContain('Fake feature detected');
  });

  it('should include color-coded verdict badge', () => {
    const data = createTestReportData({ verdict: 'SHIP' });
    const html = generateHtmlReport(data, 'full');

    expect(html).toContain('class="verdict-badge"');
    expect(html).toContain('#22c55e'); // green
  });

  it('should escape HTML entities', () => {
    const data = createTestReportData({
      files: [
        {
          file: 'src/test<script>.ts',
          status: 'FAIL',
          method: 'Specless',
          score: 0.1,
          blockers: ['Contains <script> tag'],
          finding: 'XSS via <img onerror>',
        },
      ],
    });
    const html = generateHtmlReport(data, 'full');

    expect(html).not.toContain('<script>');
    expect(html).toContain('&lt;script&gt;');
  });

  it('should support custom CSS', () => {
    const data = createTestReportData();
    const html = generateHtmlReport(data, 'full', {
      customCss: 'body { background: #000; }',
    });

    expect(html).toContain('body { background: #000; }');
  });

  it('should not show passing section in failures-only scope', () => {
    const data = createTestReportData();
    const html = generateHtmlReport(data, 'failures-only');

    expect(html).toContain('Failures');
    // The <h2>Passing</h2> section should not appear (summary table "Passing" row is OK)
    expect(html).not.toContain('<h2>Passing</h2>');
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// buildReportData Tests
// ─────────────────────────────────────────────────────────────────────────────

describe('buildReportData', () => {
  it('should adapt UnifiedVerifyResult-like data to ReportData', () => {
    const result = {
      verdict: 'WARN',
      score: 0.71,
      coverage: { specced: 10, total: 15 },
      files: [
        {
          file: 'src/auth/login.ts',
          status: 'PASS',
          mode: 'ISL verified',
          score: 0.95,
          specFile: 'src/auth/login.isl',
          blockers: [],
          errors: [],
          duration: 500,
        },
        {
          file: 'src/payments/refund.ts',
          status: 'FAIL',
          mode: 'Fake feature',
          score: 0.23,
          blockers: ['Fake feature detected'],
          errors: [],
          duration: 200,
        },
      ],
      blockers: ['src/payments/refund.ts: Fake feature detected'],
      recommendations: [
        'Generate ISL specs for src/payments/',
        'Update src/auth/login.isl',
      ],
      mode: 'mixed',
      duration: 1200,
    };

    const reportData = buildReportData(result, {
      repository: 'github.com/acme/api',
      branch: 'main',
      commit: 'abc1234',
    });

    expect(reportData.verdict).toBe('WARN');
    expect(reportData.score).toBe(0.71);
    expect(reportData.repository.repository).toBe('github.com/acme/api');
    expect(reportData.repository.branch).toBe('main');
    expect(reportData.repository.commit).toBe('abc1234');
    expect(reportData.coverage.totalFiles).toBe(15);
    expect(reportData.coverage.specCoveredFiles).toBe(10);
    expect(reportData.coverage.coveragePercent).toBe(67);
    expect(reportData.coverage.passingFiles).toBe(1);
    expect(reportData.coverage.failingFiles).toBe(1);
    expect(reportData.files).toHaveLength(2);
    expect(reportData.recommendations).toHaveLength(2);
    expect(reportData.recommendations[0]?.priority).toBe(1);
    expect(reportData.recommendations[0]?.text).toBe('Generate ISL specs for src/payments/');
    expect(reportData.generatedAt).toBeTruthy();
  });

  it('should handle empty results', () => {
    const result = {
      verdict: 'SHIP',
      score: 1.0,
      coverage: { specced: 0, total: 0 },
      files: [],
      blockers: [],
      recommendations: [],
      mode: 'isl',
      duration: 100,
    };

    const reportData = buildReportData(result, {
      repository: 'github.com/test/repo',
      branch: 'main',
    });

    expect(reportData.coverage.coveragePercent).toBe(0);
    expect(reportData.files).toHaveLength(0);
    expect(reportData.recommendations).toHaveLength(0);
  });

  it('should include trends when provided', () => {
    const result = {
      verdict: 'SHIP',
      score: 0.95,
      coverage: { specced: 5, total: 5 },
      files: [],
      blockers: [],
      recommendations: [],
      mode: 'isl',
      duration: 300,
    };

    const trends = [
      { date: '2026-02-07T00:00:00Z', coverage: 80, score: 85, label: 'PR #1' },
      { date: '2026-02-08T00:00:00Z', coverage: 100, score: 95, label: 'PR #2' },
    ];

    const reportData = buildReportData(result, {
      repository: 'github.com/test/repo',
      branch: 'main',
      trends,
    });

    expect(reportData.trends).toHaveLength(2);
    expect(reportData.trends![0]?.label).toBe('PR #1');
  });
});
