import { CodeBlock } from "@/components/CodeBlock";
import { Callout } from "@/components/docs/callout";

export const metadata = {
  title: "Validating AI Code",
  description: "Use ISL to verify code generated by AI assistants like Cursor, Copilot, and Claude.",
};

export default function ValidatingAICodePage() {
  return (
    <div>
      <h1>Validating AI-Generated Code</h1>
      <p className="lead text-xl text-muted-foreground mb-8">
        Use ISL to catch &quot;fake features&quot; and verify AI-generated code actually works.
      </p>

      <h2 id="the-problem">The Problem</h2>
      <p>
        AI assistants can generate code that looks correct but doesn&apos;t actually
        implement the intended behavior. Common issues include:
      </p>
      <ul>
        <li>Functions that return hardcoded values instead of computed results</li>
        <li>Missing error handling</li>
        <li>Incorrect edge case behavior</li>
        <li>Subtle logic bugs that pass simple tests</li>
      </ul>

      <Callout type="warning" title="Real Example">
        An AI generated a &quot;payment processing&quot; function that always returned success
        without actually charging the card. The code looked perfect but was completely fake.
      </Callout>

      <h2 id="the-solution">The Solution</h2>
      <p>
        Write ISL specifications <strong>before</strong> asking AI to generate code.
        Then verify the generated code matches your specification.
      </p>

      <h3>Step 1: Write the Specification</h3>
      <CodeBlock
        code={`intent ProcessPayment {
  pre {
    amount > 0
    card.valid
    !order.paid
  }
  
  post {
    success implies {
      payment.chargedAmount == amount
      payment.cardLastFour == card.lastFour
      order.paid == true
      receipt.generated
    }
    
    failure implies {
      order.paid == false
      payment.chargedAmount == 0
      error != null
    }
  }
}`}
        language="isl"
        filename="payment.isl"
        showLineNumbers
      />

      <h3>Step 2: Ask AI to Generate Code</h3>
      <p>Include your specification in the prompt:</p>
      <CodeBlock
        code={`Given this ISL specification for payment processing:
[paste your spec]

Generate a TypeScript implementation that:
1. Calls the Stripe API to charge the card
2. Creates a payment record in the database
3. Updates the order status
4. Generates a receipt

The implementation must satisfy all pre and post conditions.`}
        language="text"
      />

      <h3>Step 3: Verify the Implementation</h3>
      <CodeBlock
        code={`$ isl verify payment.isl --impl ./src/payment.ts

Running verification...

ProcessPayment:
  ✓ Precondition: amount > 0 (passed)
  ✓ Precondition: card.valid (passed)
  ✓ Precondition: !order.paid (passed)
  ✓ Postcondition: payment.chargedAmount == amount (passed)
  ✓ Postcondition: payment.cardLastFour == card.lastFour (passed)
  ✓ Postcondition: order.paid == true (passed)
  ✓ Postcondition: receipt.generated (passed)

All conditions verified!`}
        language="bash"
      />

      <h2 id="workflow">Recommended Workflow</h2>
      <ol>
        <li><strong>Spec First</strong> - Write ISL specification before code</li>
        <li><strong>Include in Context</strong> - Give the spec to your AI assistant</li>
        <li><strong>Generate Code</strong> - Let AI generate the implementation</li>
        <li><strong>Verify</strong> - Run <code>isl verify</code> to check compliance</li>
        <li><strong>Iterate</strong> - If verification fails, fix and re-verify</li>
      </ol>

      <h2 id="cursor-integration">Cursor Integration</h2>
      <p>
        If you&apos;re using Cursor, install the{" "}
        <a href="/docs/tools/mcp">ISL MCP server</a> for deep integration:
      </p>
      <ul>
        <li>Cursor sees your ISL specs automatically</li>
        <li>Generated code is validated in real-time</li>
        <li>Violations are highlighted immediately</li>
      </ul>

      <h2 id="common-catches">What ISL Catches</h2>
      <div className="not-prose overflow-x-auto my-6">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b">
              <th className="text-left py-2 px-3">Issue</th>
              <th className="text-left py-2 px-3">Example</th>
            </tr>
          </thead>
          <tbody>
            <tr className="border-b border-border/50">
              <td className="py-2 px-3">Fake features</td>
              <td className="py-2 px-3">Function returns hardcoded value</td>
            </tr>
            <tr className="border-b border-border/50">
              <td className="py-2 px-3">Missing validation</td>
              <td className="py-2 px-3">Preconditions not checked</td>
            </tr>
            <tr className="border-b border-border/50">
              <td className="py-2 px-3">Incomplete operations</td>
              <td className="py-2 px-3">Database not updated</td>
            </tr>
            <tr className="border-b border-border/50">
              <td className="py-2 px-3">Wrong error handling</td>
              <td className="py-2 px-3">Errors swallowed silently</td>
            </tr>
            <tr className="border-b border-border/50">
              <td className="py-2 px-3">State inconsistency</td>
              <td className="py-2 px-3">Invariants violated</td>
            </tr>
          </tbody>
        </table>
      </div>

      <Callout type="tip" title="Best Practice">
        The more specific your postconditions, the harder it is for AI to generate
        fake implementations. Include checks for actual side effects, not just return values.
      </Callout>
    </div>
  );
}
