/**
 * Go Command — One command to rule them all.
 *
 * Usage:
 *   shipgate go                   # Scan current dir, infer ISL, verify, gate
 *   shipgate go ./my-project      # Scan target dir
 *   shipgate go --fix             # Auto-heal violations after scan
 *   shipgate go --deep            # Thorough scan with higher coverage
 *
 * Pipeline: detect → init → infer ISL → truthpack → verify → gate → report
 */

import { resolve, relative, join, basename } from 'path';
import { existsSync } from 'fs';
import { mkdir, writeFile } from 'fs/promises';
import chalk from 'chalk';
import ora, { type Ora } from 'ora';
import { runProjectScan, type ProjectScanResult } from './scan.js';
import { ExitCode } from '../exit-codes.js';

export interface GoOptions {
  fix?: boolean;
  deep?: boolean;
  provider?: 'anthropic' | 'openai';
  model?: string;
  minCoverage?: number;
  format?: 'pretty' | 'json';
  verbose?: boolean;
  upload?: boolean;
  project?: string;
}

export interface GoResult {
  success: boolean;
  verdict: 'SHIP' | 'NO_SHIP' | 'WARN';
  phases: Array<{ name: string; success: boolean; duration: number; details?: string }>;
  scanResult: ProjectScanResult | null;
  duration: number;
  errors: string[];
}

export async function go(targetPath: string, options: GoOptions = {}): Promise<GoResult> {
  const startTime = Date.now();
  const resolvedPath = resolve(targetPath);
  const projectName = basename(resolvedPath);
  const isJson = options.format === 'json';
  const spinner = !isJson ? ora() : null;
  const phases: GoResult['phases'] = [];
  const errors: string[] = [];

  // ── Phase 1: Detect project ────────────────────────────────────────
  const phaseStart = Date.now();
  spinner && (spinner.text = `Detecting project: ${projectName}...`);
  spinner?.start();

  const hasShipgate = existsSync(join(resolvedPath, '.shipgate.yml')) ||
                      existsSync(join(resolvedPath, '.shipgate'));
  const hasPackageJson = existsSync(join(resolvedPath, 'package.json'));
  const hasCargoToml = existsSync(join(resolvedPath, 'Cargo.toml'));
  const hasPyProject = existsSync(join(resolvedPath, 'pyproject.toml')) ||
                       existsSync(join(resolvedPath, 'requirements.txt'));
  const hasGoMod = existsSync(join(resolvedPath, 'go.mod'));

  const detectedStack = hasCargoToml ? 'Rust'
    : hasGoMod ? 'Go'
    : hasPyProject ? 'Python'
    : hasPackageJson ? 'TypeScript/JavaScript'
    : 'Mixed/Unknown';

  phases.push({
    name: 'detect',
    success: true,
    duration: Date.now() - phaseStart,
    details: `Stack: ${detectedStack}, ShipGate initialized: ${hasShipgate ? 'yes' : 'no'}`,
  });

  spinner?.succeed(`Detected: ${detectedStack} project`);

  // ── Phase 2: Initialize ShipGate if needed ─────────────────────────
  if (!hasShipgate) {
    const initStart = Date.now();
    spinner && (spinner.text = 'Initializing ShipGate...');
    spinner?.start();

    try {
      const shipgateDir = join(resolvedPath, '.shipgate');
      await mkdir(join(shipgateDir, 'specs'), { recursive: true });
      await mkdir(join(shipgateDir, 'evidence'), { recursive: true });
      await mkdir(join(shipgateDir, 'truthpack'), { recursive: true });

      const configContent = [
        '# ShipGate Configuration',
        '# Auto-generated by `shipgate go`',
        '',
        'version: 1',
        '',
        'verify:',
        '  threshold: 70',
        '  failOn: noship',
        '',
        'scan:',
        '  exclude:',
        '    - node_modules',
        '    - dist',
        '    - build',
        '    - __pycache__',
        '    - target',
        '    - vendor',
        '    - .git',
        '',
        'ai:',
        `  provider: ${options.provider ?? 'anthropic'}`,
        '',
      ].join('\n');

      await writeFile(join(resolvedPath, '.shipgate.yml'), configContent, 'utf-8');

      phases.push({ name: 'init', success: true, duration: Date.now() - initStart });
      spinner?.succeed('ShipGate initialized');
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      errors.push(`Init failed: ${msg}`);
      phases.push({ name: 'init', success: false, duration: Date.now() - initStart, details: msg });
      spinner?.warn('ShipGate init skipped (non-fatal)');
    }
  } else {
    phases.push({ name: 'init', success: true, duration: 0, details: 'already initialized' });
  }

  // ── Phase 3: Scan + Infer ISL + Truthpack + Gate ───────────────────
  const scanStart = Date.now();
  spinner && (spinner.text = 'Scanning project, generating ISL specs, running gate...');
  spinner?.start();

  let scanResult: ProjectScanResult | null = null;
  try {
    scanResult = await runProjectScan(resolvedPath, {
      minCoverage: options.minCoverage ?? (options.deep ? 50 : 0),
      provider: options.provider,
      model: options.model,
      format: options.format,
      verbose: options.verbose,
    });

    phases.push({
      name: 'scan',
      success: scanResult.success,
      duration: Date.now() - scanStart,
      details: `${scanResult.filesScanned} files, ${scanResult.specsGenerated} specs, ${scanResult.coverage.percent}% coverage`,
    });

    if (scanResult.success) {
      spinner?.succeed(`Scan complete: ${scanResult.filesScanned} files, ${scanResult.specsGenerated} specs generated`);
    } else {
      spinner?.warn(`Scan: ${scanResult.verdict} (${scanResult.coverage.percent}% coverage)`);
    }
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    errors.push(`Scan failed: ${msg}`);
    phases.push({ name: 'scan', success: false, duration: Date.now() - scanStart, details: msg });
    spinner?.fail('Scan failed');
  }

  // ── Phase 4: Auto-heal (if --fix and violations exist) ─────────────
  if (options.fix && scanResult && scanResult.verdict !== 'SHIP') {
    const healStart = Date.now();
    spinner && (spinner.text = 'Auto-healing violations...');
    spinner?.start();

    try {
      const { heal } = await import('./heal.js');
      if (scanResult.mergedSpecPath) {
        const healResult = await heal(resolvedPath, {
          spec: scanResult.mergedSpecPath,
          maxIterations: 3,
          dryRun: false,
        });

        phases.push({
          name: 'heal',
          success: healResult.success,
          duration: Date.now() - healStart,
          details: `${healResult.fixedCount ?? 0} issues fixed`,
        });

        if (healResult.success) {
          spinner?.succeed('Auto-heal complete');
        } else {
          spinner?.warn('Some violations could not be auto-fixed');
        }
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      errors.push(`Heal failed: ${msg}`);
      phases.push({ name: 'heal', success: false, duration: Date.now() - healStart, details: msg });
      spinner?.warn('Auto-heal skipped');
    }
  }

  // ── Final verdict ──────────────────────────────────────────────────
  const verdict = scanResult?.verdict ?? 'NO_SHIP';
  const totalDuration = Date.now() - startTime;

  return {
    success: verdict !== 'NO_SHIP',
    verdict,
    phases,
    scanResult,
    duration: totalDuration,
    errors,
  };
}

export function printGoResult(result: GoResult, projectPath: string): void {
  const verdictIcon = result.verdict === 'SHIP' ? chalk.green('SHIP')
    : result.verdict === 'WARN' ? chalk.yellow('WARN')
    : chalk.red('NO_SHIP');

  console.log('');
  console.log(chalk.bold('┌──────────────────────────────────────────────────────┐'));
  console.log(chalk.bold('│              ShipGate — Project Report                │'));
  console.log(chalk.bold('├──────────────────────────────────────────────────────┤'));
  console.log(`  Verdict:   ${verdictIcon}`);
  console.log(`  Duration:  ${(result.duration / 1000).toFixed(1)}s`);
  console.log('');

  console.log(chalk.bold('  Pipeline:'));
  for (const phase of result.phases) {
    const icon = phase.success ? chalk.green('✓') : chalk.red('✗');
    const dur = chalk.gray(`(${phase.duration}ms)`);
    const detail = phase.details ? chalk.gray(` — ${phase.details}`) : '';
    console.log(`    ${icon} ${phase.name} ${dur}${detail}`);
  }

  if (result.scanResult) {
    const s = result.scanResult;
    const pct = s.coverage.percent;
    const filled = Math.round((pct / 100) * 20);
    const bar = `${'█'.repeat(filled)}${'░'.repeat(20 - filled)}`;
    console.log('');
    console.log(chalk.bold('  Coverage:'));
    console.log(`    [${bar}] ${pct}% (${s.coverage.covered}/${s.coverage.total})`);

    if (s.gateResult && s.gateResult.violations.length > 0) {
      console.log('');
      console.log(chalk.bold(`  Violations (${s.gateResult.violations.length}):`));
      for (const v of s.gateResult.violations.slice(0, 5)) {
        console.log(`    ${chalk.red('✗')} ${v}`);
      }
      if (s.gateResult.violations.length > 5) {
        console.log(chalk.gray(`    ... and ${s.gateResult.violations.length - 5} more`));
      }
    }

    if (s.mergedSpecPath) {
      console.log('');
      console.log(`  ISL spec:  ${relative(process.cwd(), s.mergedSpecPath)}`);
    }
  }

  if (result.errors.length > 0) {
    console.log('');
    console.log(chalk.bold('  Issues:'));
    for (const err of result.errors.slice(0, 5)) {
      console.log(`    ${chalk.yellow('!')} ${err}`);
    }
  }

  console.log('');
  console.log(chalk.bold('  Next steps:'));
  if (result.verdict === 'SHIP') {
    console.log(chalk.green('    Your project is safe to ship.'));
    console.log(`    ${chalk.gray('$')} shipgate gate --ci         ${chalk.gray('# Add to CI')}`);
    console.log(`    ${chalk.gray('$')} shipgate scan --upload     ${chalk.gray('# Push to dashboard')}`);
  } else if (result.verdict === 'WARN') {
    console.log(chalk.yellow('    Review generated specs and coverage gaps.'));
    if (result.scanResult?.mergedSpecPath) {
      console.log(`    ${chalk.gray('$')} shipgate verify ${relative(process.cwd(), result.scanResult.mergedSpecPath)}`);
    }
    console.log(`    ${chalk.gray('$')} shipgate go --fix          ${chalk.gray('# Auto-heal violations')}`);
  } else {
    console.log(`    ${chalk.gray('$')} shipgate go --fix          ${chalk.gray('# Auto-heal violations')}`);
    console.log(`    ${chalk.gray('$')} shipgate go --deep         ${chalk.gray('# Deeper scan')}`);
    console.log(`    ${chalk.gray('$')} shipgate heal .            ${chalk.gray('# Manual heal')}`);
  }

  console.log(chalk.bold('└──────────────────────────────────────────────────────┘'));
  console.log('');
}

export function getGoExitCode(result: GoResult): number {
  if (result.verdict === 'SHIP') return ExitCode.SUCCESS;
  if (result.verdict === 'WARN') return ExitCode.SUCCESS;
  return ExitCode.ISL_ERROR;
}
