/**
 * Go Command — One command to rule them all.
 *
 * Zero-config by design. Works without API keys via specless mode.
 * When API keys are available, also generates ISL specs for deeper coverage.
 *
 * Usage:
 *   shipgate go                   # Scan current dir (zero-config)
 *   shipgate go ./my-project      # Scan target dir
 *   shipgate go --fix             # Auto-heal violations after scan
 *   shipgate go --deep            # Thorough scan with higher coverage
 *
 * Pipeline: detect → init → specless scan → [AI specs if keys available] → provenance → gate → report
 */

import { resolve, relative, join, basename } from 'path';
import { existsSync } from 'fs';
import { mkdir, writeFile } from 'fs/promises';
import chalk from 'chalk';
import ora, { type Ora } from 'ora';
import { runProjectScan, type ProjectScanResult } from './scan.js';
import { ExitCode } from '../exit-codes.js';

export interface GoOptions {
  fix?: boolean;
  deep?: boolean;
  provider?: 'anthropic' | 'openai';
  model?: string;
  minCoverage?: number;
  format?: 'pretty' | 'json';
  verbose?: boolean;
  upload?: boolean;
  project?: string;
  /** Skip provenance scan */
  noProvenance?: boolean;
}

export interface ProvenanceSummarySnapshot {
  totalLines: number;
  aiAuthored: number;
  humanAuthored: number;
  aiPercentage: number;
  topAgent: string | null;
}

export interface GoResult {
  success: boolean;
  verdict: 'SHIP' | 'NO_SHIP' | 'WARN';
  phases: Array<{ name: string; success: boolean; duration: number; details?: string }>;
  scanResult: ProjectScanResult | null;
  provenance: ProvenanceSummarySnapshot | null;
  duration: number;
  errors: string[];
}

export async function go(targetPath: string, options: GoOptions = {}): Promise<GoResult> {
  const startTime = Date.now();
  const resolvedPath = resolve(targetPath);
  const projectName = basename(resolvedPath);
  const isJson = options.format === 'json';
  const spinner = !isJson ? ora() : null;
  const phases: GoResult['phases'] = [];
  const errors: string[] = [];

  // ── Phase 1: Detect project ────────────────────────────────────────
  const phaseStart = Date.now();
  spinner && (spinner.text = `Detecting project: ${projectName}...`);
  spinner?.start();

  const hasShipgate = existsSync(join(resolvedPath, '.shipgate.yml')) ||
                      existsSync(join(resolvedPath, '.shipgate'));
  const hasPackageJson = existsSync(join(resolvedPath, 'package.json'));
  const hasCargoToml = existsSync(join(resolvedPath, 'Cargo.toml'));
  const hasPyProject = existsSync(join(resolvedPath, 'pyproject.toml')) ||
                       existsSync(join(resolvedPath, 'requirements.txt'));
  const hasGoMod = existsSync(join(resolvedPath, 'go.mod'));

  const detectedStack = hasCargoToml ? 'Rust'
    : hasGoMod ? 'Go'
    : hasPyProject ? 'Python'
    : hasPackageJson ? 'TypeScript/JavaScript'
    : 'Mixed/Unknown';

  phases.push({
    name: 'detect',
    success: true,
    duration: Date.now() - phaseStart,
    details: `Stack: ${detectedStack}, ShipGate initialized: ${hasShipgate ? 'yes' : 'no'}`,
  });

  spinner?.succeed(`Detected: ${detectedStack} project`);

  // ── Phase 2: Initialize ShipGate if needed ─────────────────────────
  if (!hasShipgate) {
    const initStart = Date.now();
    spinner && (spinner.text = 'Initializing ShipGate...');
    spinner?.start();

    try {
      const shipgateDir = join(resolvedPath, '.shipgate');
      await mkdir(join(shipgateDir, 'specs'), { recursive: true });
      await mkdir(join(shipgateDir, 'evidence'), { recursive: true });
      await mkdir(join(shipgateDir, 'truthpack'), { recursive: true });

      const configContent = [
        '# ShipGate Configuration',
        '# Auto-generated by `shipgate go`',
        '',
        'version: 1',
        '',
        'verify:',
        '  threshold: 70',
        '  failOn: noship',
        '',
        'scan:',
        '  exclude:',
        '    - node_modules',
        '    - dist',
        '    - build',
        '    - __pycache__',
        '    - target',
        '    - vendor',
        '    - .git',
        '',
        'ai:',
        `  provider: ${options.provider ?? 'anthropic'}`,
        '',
      ].join('\n');

      await writeFile(join(resolvedPath, '.shipgate.yml'), configContent, 'utf-8');

      phases.push({ name: 'init', success: true, duration: Date.now() - initStart });
      spinner?.succeed('ShipGate initialized');
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      errors.push(`Init failed: ${msg}`);
      phases.push({ name: 'init', success: false, duration: Date.now() - initStart, details: msg });
      spinner?.warn('ShipGate init skipped (non-fatal)');
    }
  } else {
    phases.push({ name: 'init', success: true, duration: 0, details: 'already initialized' });
  }

  // ── Phase 3: Scan + Infer ISL + Truthpack + Gate ───────────────────
  const hasAIKeys = !!(process.env.ANTHROPIC_API_KEY || process.env.OPENAI_API_KEY);
  const scanStart = Date.now();

  if (hasAIKeys) {
    spinner && (spinner.text = 'Scanning project, generating ISL specs, running gate...');
  } else {
    spinner && (spinner.text = 'Scanning project (specless mode — no API keys needed)...');
  }
  spinner?.start();

  let scanResult: ProjectScanResult | null = null;
  try {
    scanResult = await runProjectScan(resolvedPath, {
      minCoverage: options.minCoverage ?? (options.deep ? 50 : 0),
      provider: options.provider,
      model: options.model,
      format: options.format,
      verbose: options.verbose,
    });

    phases.push({
      name: 'scan',
      success: scanResult.success,
      duration: Date.now() - scanStart,
      details: `${scanResult.filesScanned} files, ${scanResult.specsGenerated} specs, ${scanResult.coverage.percent}% coverage`,
    });

    if (scanResult.success) {
      spinner?.succeed(`Scan complete: ${scanResult.filesScanned} files, ${scanResult.specsGenerated} specs generated`);
    } else {
      spinner?.warn(`Scan: ${scanResult.verdict} (${scanResult.coverage.percent}% coverage)`);
    }
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    errors.push(`Scan failed: ${msg}`);
    phases.push({ name: 'scan', success: false, duration: Date.now() - scanStart, details: msg });
    spinner?.fail('Scan failed');
  }

  // ── Phase 3b: Specless fallback when no specs were generated ──────
  // Ensures `shipgate go` always delivers value, even without API keys.
  if (scanResult && scanResult.specsGenerated === 0 && scanResult.filesScanned > 0) {
    const speclessStart = Date.now();
    spinner && (spinner.text = 'Running specless security checks (no API keys required)...');
    spinner?.start();

    try {
      const { gate } = await import('./gate.js');
      const speclessResult = await gate({
        path: resolvedPath,
        mode: 'specless',
        threshold: options.minCoverage ?? 70,
      });

      const speclessViolations = speclessResult.violations?.length ?? 0;
      const speclessScore = speclessResult.score ?? 0;

      if (!scanResult.gateResult) {
        scanResult.gateResult = {
          verdict: speclessResult.verdict ?? 'WARN',
          score: speclessScore,
          violations: speclessResult.violations ?? [],
        };
        scanResult.verdict = speclessResult.verdict ?? 'WARN';
      }

      phases.push({
        name: 'specless',
        success: speclessViolations === 0,
        duration: Date.now() - speclessStart,
        details: `${speclessViolations} findings, score: ${speclessScore}`,
      });

      spinner?.succeed(`Specless checks: ${speclessViolations} findings (score: ${speclessScore})`);
    } catch {
      phases.push({
        name: 'specless',
        success: true,
        duration: Date.now() - speclessStart,
        details: 'specless checks skipped',
      });
      spinner?.info('Specless checks skipped');
    }
  }

  // ── Phase 3c: Provenance snapshot ─────────────────────────────────
  let provenance: ProvenanceSummarySnapshot | null = null;
  if (!options.noProvenance) {
    const provStart = Date.now();
    spinner && (spinner.text = 'Scanning code provenance (AI attribution)...');
    spinner?.start();

    try {
      const { buildProjectAttribution, getAgentDisplayName } = await import('@isl-lang/code-provenance');
      const attr = buildProjectAttribution({
        cwd: resolvedPath,
        maxFiles: 100,
      });

      let topAgentName: string | null = null;
      let topAgentCount = 0;
      for (const [agent, count] of Object.entries(attr.summary.byAgent)) {
        if ((count ?? 0) > topAgentCount) {
          topAgentCount = count ?? 0;
          topAgentName = getAgentDisplayName(agent as any);
        }
      }

      provenance = {
        totalLines: attr.summary.totalLines,
        aiAuthored: attr.summary.aiAuthored,
        humanAuthored: attr.summary.humanAuthored,
        aiPercentage: attr.summary.totalLines > 0
          ? Math.round((attr.summary.aiAuthored / attr.summary.totalLines) * 100)
          : 0,
        topAgent: topAgentName,
      };

      phases.push({
        name: 'provenance',
        success: true,
        duration: Date.now() - provStart,
        details: `${provenance.totalLines} lines, ${provenance.aiPercentage}% AI-authored`,
      });

      spinner?.succeed(`Provenance: ${provenance.totalLines} lines, ${provenance.aiPercentage}% AI-authored`);
    } catch {
      phases.push({
        name: 'provenance',
        success: true,
        duration: Date.now() - provStart,
        details: 'provenance skipped (not in git repo)',
      });
      spinner?.info('Provenance scan skipped');
    }
  }

  // ── Phase 4: Auto-heal (if --fix and violations exist) ─────────────
  if (options.fix && scanResult && scanResult.verdict !== 'SHIP') {
    const healStart = Date.now();
    spinner && (spinner.text = 'Auto-healing violations...');
    spinner?.start();

    try {
      const { heal } = await import('./heal.js');
      if (scanResult.mergedSpecPath) {
        const healResult = await heal(resolvedPath, {
          spec: scanResult.mergedSpecPath,
          maxIterations: 3,
          dryRun: false,
        });

        phases.push({
          name: 'heal',
          success: healResult.success,
          duration: Date.now() - healStart,
          details: `${healResult.fixedCount ?? 0} issues fixed`,
        });

        if (healResult.success) {
          spinner?.succeed('Auto-heal complete');
        } else {
          spinner?.warn('Some violations could not be auto-fixed');
        }
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      errors.push(`Heal failed: ${msg}`);
      phases.push({ name: 'heal', success: false, duration: Date.now() - healStart, details: msg });
      spinner?.warn('Auto-heal skipped');
    }
  }

  // ── Final verdict ──────────────────────────────────────────────────
  const verdict = scanResult?.verdict ?? 'NO_SHIP';
  const totalDuration = Date.now() - startTime;

  return {
    success: verdict !== 'NO_SHIP',
    verdict,
    phases,
    scanResult,
    provenance,
    duration: totalDuration,
    errors,
  };
}

export function printGoResult(result: GoResult, projectPath: string): void {
  const verdictIcon = result.verdict === 'SHIP' ? chalk.green('SHIP')
    : result.verdict === 'WARN' ? chalk.yellow('WARN')
    : chalk.red('NO_SHIP');

  console.log('');
  console.log(chalk.bold('┌──────────────────────────────────────────────────────┐'));
  console.log(chalk.bold('│              ShipGate — Project Report                │'));
  console.log(chalk.bold('├──────────────────────────────────────────────────────┤'));
  console.log(`  Verdict:   ${verdictIcon}`);
  console.log(`  Duration:  ${(result.duration / 1000).toFixed(1)}s`);
  console.log('');

  console.log(chalk.bold('  Pipeline:'));
  for (const phase of result.phases) {
    const icon = phase.success ? chalk.green('✓') : chalk.red('✗');
    const dur = chalk.gray(`(${phase.duration}ms)`);
    const detail = phase.details ? chalk.gray(` — ${phase.details}`) : '';
    console.log(`    ${icon} ${phase.name} ${dur}${detail}`);
  }

  if (result.scanResult) {
    const s = result.scanResult;
    const pct = s.coverage.percent;
    const filled = Math.round((pct / 100) * 20);
    const bar = `${'█'.repeat(filled)}${'░'.repeat(20 - filled)}`;
    console.log('');
    console.log(chalk.bold('  Coverage:'));
    console.log(`    [${bar}] ${pct}% (${s.coverage.covered}/${s.coverage.total})`);

    if (s.gateResult && s.gateResult.violations.length > 0) {
      console.log('');
      console.log(chalk.bold(`  Violations (${s.gateResult.violations.length}):`));
      for (const v of s.gateResult.violations.slice(0, 5)) {
        console.log(`    ${chalk.red('✗')} ${v}`);
      }
      if (s.gateResult.violations.length > 5) {
        console.log(chalk.gray(`    ... and ${s.gateResult.violations.length - 5} more`));
      }
    }

    if (s.mergedSpecPath) {
      console.log('');
      console.log(`  ISL spec:  ${relative(process.cwd(), s.mergedSpecPath)}`);
    }
  }

  const allIssues = [
    ...result.errors,
    ...(result.scanResult?.errors ?? []),
  ];
  if (allIssues.length > 0) {
    console.log('');
    console.log(chalk.bold('  Issues:'));
    for (const err of allIssues.slice(0, 8)) {
      console.log(`    ${chalk.yellow('!')} ${err}`);
    }
    if (allIssues.length > 8) {
      console.log(chalk.gray(`    ... and ${allIssues.length - 8} more`));
    }
  }

  // ── Provenance summary ─────────────────────────────────────────────
  if (result.provenance) {
    const p = result.provenance;
    console.log('');
    console.log(chalk.bold('  Code Provenance:'));
    const humanPct = p.totalLines > 0 ? Math.round((p.humanAuthored / p.totalLines) * 100) : 0;
    console.log(`    ${chalk.green(`${humanPct}% Human`)}  ${chalk.magenta(`${p.aiPercentage}% AI`)}  ${chalk.gray(`(${p.totalLines.toLocaleString()} total lines)`)}`);
    if (p.topAgent) {
      console.log(`    Top AI agent: ${chalk.magenta(p.topAgent)}`);
    }
    console.log(`    ${chalk.gray('$')} shipgate provenance        ${chalk.gray('# Full audit trail')}`);
  } else {
    const provenancePhase = result.phases.find((p) => p.name === 'provenance');
    console.log('');
    console.log(chalk.bold('  Code Provenance:'));
    if (provenancePhase?.details?.includes('not in git repo')) {
      console.log(chalk.gray('    Not available — project is not a git repository.'));
      console.log(chalk.gray('    Initialize git and commit your code to enable provenance tracking.'));
    } else {
      console.log(chalk.gray('    Skipped — run separately:'));
    }
    console.log(`    ${chalk.gray('$')} shipgate provenance init   ${chalk.gray('# Install pre-commit hook for AI tagging')}`);
    console.log(`    ${chalk.gray('$')} shipgate provenance        ${chalk.gray('# Full audit trail')}`);
  }

  console.log('');
  console.log(chalk.bold('  Next steps:'));
  if (result.scanResult && result.scanResult.specsGenerated === 0 && result.scanResult.filesScanned > 0) {
    console.log(chalk.gray('    Specless mode — security checks ran without ISL specs.'));
    console.log(chalk.gray('    For deeper verification, set ANTHROPIC_API_KEY or OPENAI_API_KEY.'));
    console.log('');
  }
  if (result.verdict === 'SHIP') {
    console.log(chalk.green('    Your project is safe to ship.'));
    console.log(`    ${chalk.gray('$')} shipgate gate --ci         ${chalk.gray('# Add to CI')}`);
    console.log(`    ${chalk.gray('$')} shipgate provenance        ${chalk.gray('# AI audit trail')}`);
    console.log(`    ${chalk.gray('$')} shipgate scan --upload     ${chalk.gray('# Push to dashboard')}`);
  } else if (result.verdict === 'WARN') {
    console.log(chalk.yellow('    Review findings and coverage gaps.'));
    if (result.scanResult?.mergedSpecPath) {
      console.log(`    ${chalk.gray('$')} shipgate verify ${relative(process.cwd(), result.scanResult.mergedSpecPath)}`);
    }
    console.log(`    ${chalk.gray('$')} shipgate go --fix          ${chalk.gray('# Auto-heal violations')}`);
    console.log(`    ${chalk.gray('$')} shipgate provenance        ${chalk.gray('# AI audit trail')}`);
  } else {
    console.log(`    ${chalk.gray('$')} shipgate go --fix          ${chalk.gray('# Auto-heal violations')}`);
    console.log(`    ${chalk.gray('$')} shipgate go --deep         ${chalk.gray('# Deeper scan')}`);
    console.log(`    ${chalk.gray('$')} shipgate provenance        ${chalk.gray('# AI audit trail')}`);
    console.log(`    ${chalk.gray('$')} shipgate heal .            ${chalk.gray('# Manual heal')}`);
  }

  console.log(chalk.bold('└──────────────────────────────────────────────────────┘'));
  console.log('');
}

export function getGoExitCode(result: GoResult): number {
  if (result.verdict === 'SHIP') return ExitCode.SUCCESS;
  if (result.verdict === 'WARN') return ExitCode.SUCCESS;
  return ExitCode.ISL_ERROR;
}
