// ============================================================================
// TypeScript Type Emitter
// Generates TS interfaces/enums from the DomainUIModel
// ============================================================================

import type { DomainUIModel, EnumUIModel, EntityUIModel, BehaviorUIModel } from '../types.js';

export function emitTypes(model: DomainUIModel): string {
  const lines: string[] = [];
  lines.push('// Auto-generated by @isl-lang/ui-generator — DO NOT EDIT');
  lines.push('');

  for (const e of model.enums) {
    lines.push(`export enum ${e.name} {`);
    for (const v of e.values) {
      lines.push(`  ${v} = '${v}',`);
    }
    lines.push('}');
    lines.push('');
  }

  for (const entity of model.entities) {
    lines.push(`export interface ${entity.name} {`);
    for (const f of entity.fields) {
      const opt = f.optional ? '?' : '';
      lines.push(`  ${f.name}${opt}: ${f.tsType};`);
    }
    lines.push('}');
    lines.push('');
  }

  for (const behavior of model.behaviors) {
    if (behavior.inputFields.length > 0) {
      lines.push(`export interface ${behavior.name}Input {`);
      for (const f of behavior.inputFields) {
        const opt = f.optional ? '?' : '';
        lines.push(`  ${f.name}${opt}: ${f.tsType};`);
      }
      lines.push('}');
      lines.push('');
    }
  }

  return lines.join('\n');
}
