# ShipGate configuration for IntentOS monorepo
# Scopes verification to avoid scanning 4600+ files

version: 1

ci:
  # Exclude generated code, tests, and heavy packages
  ignore:
    - "**/node_modules/**"
    - "**/dist/**"
    - "**/*.test.*"
    - "**/*.spec.*"
    - "**/*.d.ts"
    - "**/fixtures/**"
    - "**/__tests__/**"
    - "**/golden/**"
    - "**/.next/**"
    - "**/coverage/**"
    - "packages/**"
