/**
 * ISL Adapters - PR Comment Generator
 * 
 * Generates markdown PR comments for gate results.
 * 
 * @module @isl-lang/adapters/github
 */

import type { GateResult, GateReason } from '@isl-lang/gate';

/**
 * Generate a PR comment body from gate result
 */
export function generatePRComment(result: GateResult): string {
  const verdictEmoji = result.verdict === 'SHIP' ? '✅' : '🛑';
  const verdictColor = result.verdict === 'SHIP' ? '2ea44f' : 'cf222e';
  
  const lines: string[] = [];

  // Header
  lines.push(`## ${verdictEmoji} ISL Gate: ${result.verdict}`);
  lines.push('');
  
  // Score badge
  lines.push(`**Score:** ${result.score}/100`);
  lines.push('');

  // Summary table
  if (result.reasons.length > 0) {
    lines.push('### Issues Found');
    lines.push('');
    lines.push('| Severity | Code | Message |');
    lines.push('|----------|------|---------|');
    
    for (const reason of result.reasons) {
      const severityEmoji = getSeverityEmoji(reason.severity);
      lines.push(`| ${severityEmoji} ${reason.severity ?? 'info'} | \`${reason.code}\` | ${reason.message} |`);
    }
    lines.push('');
  }

  // Affected files
  const affectedFiles = getAffectedFiles(result.reasons);
  if (affectedFiles.length > 0) {
    lines.push('<details>');
    lines.push(`<summary>📁 Affected Files (${affectedFiles.length})</summary>`);
    lines.push('');
    for (const file of affectedFiles.slice(0, 20)) {
      lines.push(`- \`${file}\``);
    }
    if (affectedFiles.length > 20) {
      lines.push(`- ... and ${affectedFiles.length - 20} more`);
    }
    lines.push('');
    lines.push('</details>');
    lines.push('');
  }

  // Provenance summary (if available)
  if ((result as any).provenance) {
    const prov = (result as any).provenance as {
      totalLines: number;
      aiAuthored: number;
      humanAuthored: number;
      aiPercentage: number;
      topAgent: string | null;
    };
    lines.push('### 🔍 Code Provenance');
    lines.push('');
    lines.push(`| Metric | Value |`);
    lines.push(`|--------|-------|`);
    lines.push(`| Total Lines | ${prov.totalLines.toLocaleString()} |`);
    lines.push(`| Human-Authored | ${prov.humanAuthored.toLocaleString()} (${100 - prov.aiPercentage}%) |`);
    lines.push(`| AI-Assisted | ${prov.aiAuthored.toLocaleString()} (${prov.aiPercentage}%) |`);
    if (prov.topAgent) {
      lines.push(`| Top AI Agent | ${prov.topAgent} |`);
    }
    lines.push('');
    lines.push('> Run `shipgate provenance` for line-level attribution details.');
    lines.push('');
  }

  // Footer
  lines.push('---');
  lines.push(`<sub>Generated by ISL Gate | Fingerprint: \`${result.fingerprint}\` | Duration: ${result.durationMs}ms</sub>`);

  return lines.join('\n');
}

/**
 * Generate a compact PR comment (for updates)
 */
export function generateCompactComment(result: GateResult): string {
  const verdictEmoji = result.verdict === 'SHIP' ? '✅' : '🛑';
  const issueCount = result.reasons.length;
  
  return `${verdictEmoji} **ISL Gate: ${result.verdict}** | Score: ${result.score}/100 | Issues: ${issueCount}`;
}

/**
 * Generate SARIF output for GitHub Security tab
 */
export function generateSARIF(result: GateResult, projectRoot: string): object {
  return {
    $schema: 'https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json',
    version: '2.1.0',
    runs: [
      {
        tool: {
          driver: {
            name: 'ISL Gate',
            version: '0.1.0',
            informationUri: 'https://github.com/isl-lang/isl',
            rules: result.reasons.map(r => ({
              id: r.code,
              name: r.code,
              shortDescription: { text: r.message },
              defaultConfiguration: {
                level: mapSeverityToSARIF(r.severity),
              },
            })),
          },
        },
        results: result.reasons.flatMap(r =>
          r.files.map(file => ({
            ruleId: r.code,
            message: { text: r.message },
            level: mapSeverityToSARIF(r.severity),
            locations: [
              {
                physicalLocation: {
                  artifactLocation: {
                    uri: file,
                    uriBaseId: '%SRCROOT%',
                  },
                },
              },
            ],
          }))
        ),
      },
    ],
  };
}

// Helpers

function getSeverityEmoji(severity?: string): string {
  switch (severity) {
    case 'critical': return '🔴';
    case 'high': return '🟠';
    case 'medium': return '🟡';
    case 'low': return '🟢';
    default: return '⚪';
  }
}

function getAffectedFiles(reasons: GateReason[]): string[] {
  const files = new Set<string>();
  for (const reason of reasons) {
    for (const file of reason.files) {
      files.add(file);
    }
  }
  return [...files].sort();
}

function mapSeverityToSARIF(severity?: string): string {
  switch (severity) {
    case 'critical':
    case 'high':
      return 'error';
    case 'medium':
      return 'warning';
    default:
      return 'note';
  }
}
