// Auto-generated by @isl-lang/ui-generator — DO NOT EDIT

export interface Account {
  id: string;
  balance: number;
  isActive: boolean;
}

export interface TransferFundsInput {
  senderId: string;
  receiverId: string;
  amount: number;
}
