// Auto-generated by @isl-lang/ui-generator — DO NOT EDIT

export function validateAccount(values: Record<string, unknown>): Record<string, string> {
  const errors: Record<string, string> = {};
  if (values['id'] == null || values['id'] === '') {
    errors['id'] = "Id is required";
  }
  if (values['id'] != null && !new RegExp("^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$").test(String(values['id']))) {
    errors['id'] = "Id must be a valid UUID";
  }
  if (values['balance'] == null || values['balance'] === '') {
    errors['balance'] = "Balance is required";
  }
  if (values['isActive'] == null || values['isActive'] === '') {
    errors['isActive'] = "Is Active is required";
  }
  return errors;
}

export function validateTransferFunds(values: Record<string, unknown>): Record<string, string> {
  const errors: Record<string, string> = {};
  if (values['senderId'] == null || values['senderId'] === '') {
    errors['senderId'] = "Sender Id is required";
  }
  if (values['senderId'] != null && !new RegExp("^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$").test(String(values['senderId']))) {
    errors['senderId'] = "Sender Id must be a valid UUID";
  }
  if (values['receiverId'] == null || values['receiverId'] === '') {
    errors['receiverId'] = "Receiver Id is required";
  }
  if (values['receiverId'] != null && !new RegExp("^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$").test(String(values['receiverId']))) {
    errors['receiverId'] = "Receiver Id must be a valid UUID";
  }
  if (values['amount'] == null || values['amount'] === '') {
    errors['amount'] = "Amount is required";
  }
  if (Number(values['amount']) < 1) {
    errors['amount'] = "Amount must be at least 1";
  }
  return errors;
}
