/**
 * Prisma Schema Generator
 *
 * Converts ISL entity definitions into a Prisma schema.
 * @module @isl-lang/codegen-fullstack/prisma-generator
 */

import type { GeneratedSpec, EntitySpec, EntityField } from '@isl-lang/spec-generator';

const ISL_TO_PRISMA_TYPE: Record<string, string> = {
  String: 'String',
  Int: 'Int',
  Decimal: 'Decimal',
  Boolean: 'Boolean',
  DateTime: 'DateTime',
  UUID: 'String',
  Email: 'String',
  URL: 'String',
  Float: 'Float',
  JSON: 'Json',
};

function toPrismaField(field: EntityField, allEntityNames: Set<string>): string {
  const isOptional = field.modifiers?.includes('optional') || field.optional;
  const isUnique = field.modifiers?.includes('unique');
  const isImmutable = field.modifiers?.includes('immutable');
  const hasDefault = field.modifiers?.find((m) => m.startsWith('default:'));
  const isRelation = allEntityNames.has(field.type);

  let prismaType: string;
  let annotations: string[] = [];

  if (field.name === 'id') {
    return `  id     String  @id @default(cuid())`;
  }

  if (field.name === 'createdAt') {
    return `  createdAt DateTime @default(now())`;
  }

  if (field.name === 'updatedAt') {
    return `  updatedAt DateTime @updatedAt`;
  }

  if (isRelation) {
    const refType = `${field.type}${isOptional ? '?' : ''}`;
    const fieldId = `${field.name}Id`;
    return [
      `  ${field.name}   ${refType} @relation(fields: [${fieldId}], references: [id])`,
      `  ${fieldId} String${isOptional ? '?' : ''}`,
    ].join('\n');
  }

  prismaType = ISL_TO_PRISMA_TYPE[field.type] ?? 'String';
  if (isOptional) prismaType += '?';

  if (isUnique) annotations.push('@unique');
  if (hasDefault) {
    const val = hasDefault.split(':')[1]?.trim();
    if (val !== undefined) {
      if (prismaType.startsWith('Boolean')) annotations.push(`@default(${val})`);
      else if (prismaType.startsWith('String')) annotations.push(`@default("${val}")`);
      else annotations.push(`@default(${val})`);
    }
  }

  const annotStr = annotations.length ? ` ${annotations.join(' ')}` : '';
  return `  ${field.name.padEnd(16)} ${prismaType}${annotStr}`;
}

function generateModelBlock(entity: EntitySpec, allEntityNames: Set<string>): string {
  const lines: string[] = [`model ${entity.name} {`];
  for (const field of entity.fields) {
    lines.push(toPrismaField(field, allEntityNames));
  }
  lines.push('}');
  return lines.join('\n');
}

export function generatePrismaSchema(spec: GeneratedSpec, provider: string = 'postgresql'): string {
  const allEntityNames = new Set(spec.entities.map((e) => e.name));

  const header = `// Generated by ShipGate from ISL spec: ${spec.domainName} v${spec.version}
// DO NOT EDIT — regenerate using: shipgate generate

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "${provider}"
  url      = env("DATABASE_URL")
}
`;

  const models = spec.entities
    .map((e) => generateModelBlock(e, allEntityNames))
    .join('\n\n');

  return `${header}\n${models}\n`;
}
