/**
 * Auto-generated by ISL CLI
 * DO NOT EDIT - regenerate with: isl gen typescript ..\..\test-fixtures\valid\minimal.isl
 * Generated: 2026-02-03T06:59:48.080Z
 */

// Types generated from ISL specification

export interface Item {
  id: string;
}
