/**
 * Test helpers template - Request builder, response assertion helpers.
 */

import type { TestInfrastructureContext } from './types.js';

export function generateHelpersContent(ctx: TestInfrastructureContext): string {
  const { hasAuth = false } = ctx;

  const authImport = hasAuth ? `import { authHeaders } from '../setup.js';` : '';
  const authSpread = hasAuth ? '...authHeaders(),' : '';

  return `/**
 * Test helpers - Request builder, response assertions
 * @generated by build-runner
 */
${authImport}

export interface RequestBuilderOptions {
  method?: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  body?: unknown;
  headers?: Record<string, string>;
  baseUrl?: string;
}

export function buildRequest(path: string, options: RequestBuilderOptions = {}): RequestInit & { url: string } {
  const { method = 'GET', body, headers = {}, baseUrl = 'http://localhost:3000' } = options;
  const url = path.startsWith('http') ? path : \`\${baseUrl}\${path.startsWith('/') ? '' : '/'}\${path}\`;

  const init: RequestInit & { url: string } = {
    method,
    headers: {
      'Content-Type': 'application/json',
      ${authSpread}
      ...headers,
    },
    url,
  } as RequestInit & { url: string };

  if (body !== undefined && method !== 'GET') {
    init.body = JSON.stringify(body);
  }

  return init;
}

export async function fetchJson<T = unknown>(path: string, options?: RequestBuilderOptions): Promise<{ status: number; data: T }> {
  const { url, ...init } = buildRequest(path, options);
  const res = await fetch(url, init as RequestInit);
  const data = (await res.json().catch(() => ({}))) as T;
  return { status: res.status, data };
}

export function assertSuccess<T>(res: { status: number; data: T }): asserts res is { status: 200 | 201; data: T } {
  if (res.status < 200 || res.status >= 300) {
    throw new Error(\`Expected success status, got \${res.status}: \${JSON.stringify(res.data)}\`);
  }
}

export function assertError(res: { status: number; data: unknown }, expectedStatus?: number): void {
  if (res.status >= 200 && res.status < 300) {
    throw new Error(\`Expected error status, got \${res.status}\`);
  }
  if (expectedStatus !== undefined && res.status !== expectedStatus) {
    throw new Error(\`Expected status \${expectedStatus}, got \${res.status}\`);
  }
}
`;
}
