/**
 * Test setup template - DB setup, Prisma mock, auth helpers.
 * Generates valid JWT for protected routes.
 */

import type { TestInfrastructureContext } from './types.js';

export function generateSetupContent(ctx: TestInfrastructureContext): string {
  const { hasPrisma = true, hasAuth = false } = ctx;

  const prismaMock = hasPrisma
    ? `
// ─── Prisma Mock ─────────────────────────────────────────────────────────
import { vi } from 'vitest';

// Mock PrismaClient before any imports that use it
vi.mock('@prisma/client', () => ({
  PrismaClient: vi.fn().mockImplementation(() => ({
    $connect: vi.fn().mockResolvedValue(undefined),
    $disconnect: vi.fn().mockResolvedValue(undefined),
    user: createModelMock('user'),
    // Add other models from your Prisma schema as needed
  })),
}));

function createModelMock(modelName: string) {
  return {
    findMany: vi.fn().mockResolvedValue([]),
    findUnique: vi.fn().mockResolvedValue(null),
    findFirst: vi.fn().mockResolvedValue(null),
    create: vi.fn().mockImplementation((args) => ({ id: 'mock-id', ...args.data })),
    update: vi.fn().mockImplementation((args) => ({ id: args.where?.id, ...args.data })),
    delete: vi.fn().mockResolvedValue({}),
    count: vi.fn().mockResolvedValue(0),
  };
}
`
    : '';

  const authHelpers = hasAuth
    ? `
// ─── Auth Helpers (JWT for protected routes) ───────────────────────────────
export function createTestJWT(payload: Record<string, unknown> = {}): string {
  const header = Buffer.from(JSON.stringify({ alg: 'HS256', typ: 'JWT' })).toString('base64url');
  const body = Buffer.from(JSON.stringify({ sub: 'test-user-id', exp: Math.floor(Date.now()/1000) + 3600, ...payload })).toString('base64url');
  const signature = Buffer.from('test-sig').toString('base64url');
  return \`\${header}.\${body}.\${signature}\`;
}

export function authHeaders(token?: string): Record<string, string> {
  const t = token ?? createTestJWT();
  return { Authorization: \`Bearer \${t}\` };
}
`
    : '';

  return `/**
 * Test setup - Prisma mock, auth helpers, global config
 * @generated by build-runner
 */
import { beforeAll, afterAll, vi } from 'vitest';
${prismaMock}
${authHelpers}
beforeAll(() => {
  vi.useFakeTimers();
});

afterAll(() => {
  vi.useRealTimers();
});
`;
}
