version: "1.0"

specs:
  include:
    - "src/**/*.isl"

verify:
  strict: true
  policies:
    auth:
      enabled: true
    rate-limit:
      enabled: true
    pii:
      enabled: true

evidence:
  output_dir: ".shipgate/evidence"
