/**
 * ShipGate Init Template
 *
 * Starter .shipgate.yml content generated by `shipgate init`.
 */

/** Generate the starter .shipgate.yml content */
export function generateStarterConfig(): string {
  return `# .shipgate.yml — ShipGate configuration
# Docs: https://shipgate.dev/docs/config
version: 1

ci:
  fail_on: error
  # require_isl:
  #   - src/auth/**
  #   - src/payments/**
  # ignore: extends defaults (node_modules, dist, .next, etc.); add patterns below:
  ignore:
    - "**/*.test.ts"
    - "**/*.spec.ts"
    - src/generated/**
  specless_mode: "on"

scanning:
  hallucinations: true
  fake_features: true
  secrets: true
  vulnerabilities: true

generate:
  output: .shipgate/specs
  min_confidence: 0.3
`;
}
