/**
 * Auto-generated by ISL CLI
 * DO NOT EDIT - regenerate with: isl gen typescript examples\minimal.isl
 * Generated: 2026-02-07T12:01:54.732Z
 */

// Types generated from ISL specification

export interface User {
  id: string;
}

export type CreateUserFn = () => Promise<unknown>;

export interface CreateUserHandler {
  createUser(): Promise<unknown>;
}
