# ShipGate PR Gate — Template for simple repos (Next.js, etc.)
#
# Copy to .github/workflows/shipgate.yml
#
# Prerequisites:
#   1. Add shipgate as devDependency: pnpm add -D shipgate
#   2. (Optional) Create .shipgate.yml for config
#
# Config: Set repo variable SHIPGATE_FAIL_ON = warning to also fail on WARN

name: ShipGate

on:
  pull_request:
    branches: [main, master]
    types: [opened, synchronize, reopened]

concurrency:
  group: shipgate-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shipgate-verify:
    name: ShipGate Verify
    runs-on: ubuntu-latest
    env:
      SHIPGATE_FAIL_ON: ${{ vars.SHIPGATE_FAIL_ON || 'error' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        # For npm: run: npm ci

      - name: Create reports directory
        run: mkdir -p .shipgate/reports

      - name: Run ShipGate Verify
        id: shipgate
        run: |
          set +e
          npx shipgate verify . --ci --fail-on "$SHIPGATE_FAIL_ON" --format github > .shipgate/reports/ci.json
          EXIT_CODE=$?
          set -e

          VERDICT=$(jq -r '.verdict // "UNKNOWN"' .shipgate/reports/ci.json 2>/dev/null || echo "UNKNOWN")
          TRUST_SCORE=$(jq -r '.trustScore // 0' .shipgate/reports/ci.json 2>/dev/null || echo "0")
          SUMMARY=$(jq -r '.summary // ""' .shipgate/reports/ci.json 2>/dev/null || echo "")

          echo "verdict=$VERDICT" >> $GITHUB_OUTPUT
          echo "trust_score=$TRUST_SCORE" >> $GITHUB_OUTPUT

          echo "## ShipGate Verification" >> $GITHUB_STEP_SUMMARY
          echo "**Verdict:** \`$VERDICT\` | **Trust Score:** $TRUST_SCORE/100" >> $GITHUB_STEP_SUMMARY
          if [ "$VERDICT" = "NO_SHIP" ]; then
            echo "::error::ShipGate: NO_SHIP — verification failed"
          elif [ "$VERDICT" = "WARN" ]; then
            echo "::warning::ShipGate: WARN — review recommended"
          fi

          exit $EXIT_CODE

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: shipgate-report
          path: .shipgate/reports/ci.json
          retention-days: 30
          if-no-files-found: warn

  comment:
    name: PR Comment
    runs-on: ubuntu-latest
    needs: shipgate-verify
    if: always() && github.event_name == 'pull_request' && (needs.shipgate-verify.result == 'success' || needs.shipgate-verify.result == 'failure')
    permissions:
      pull-requests: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: shipgate-report
          path: .shipgate/reports/
        continue-on-error: true

      - uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let verdict = 'UNKNOWN', trustScore = 0, summary = '', reportJson = '{}';
            try {
              const r = JSON.parse(fs.readFileSync('.shipgate/reports/ci.json', 'utf8'));
              verdict = r.verdict || 'UNKNOWN';
              trustScore = r.trustScore ?? 0;
              summary = r.summary || '';
              reportJson = JSON.stringify(r, null, 2);
            } catch (e) { reportJson = 'Report not available'; }
            const emoji = verdict === 'SHIP' ? '✅' : verdict === 'NO_SHIP' ? '❌' : '⚠️';
            const status = verdict === 'SHIP' ? 'passed' : verdict === 'NO_SHIP' ? 'failed' : 'needs review';
            const body = `## ${emoji} ShipGate: ${status}\n\n**Verdict:** \`${verdict}\` | **Trust Score:** ${trustScore}/100\n\n${summary ? `> ${summary}\n\n` : ''}<details><summary>Full report</summary>\n\n\`\`\`json\n${reportJson}\n\`\`\`\n</details>\n\n---\n*ShipGate PR gate*`;
            const { data: comments } = await github.rest.issues.listComments({ owner: context.repo.owner, repo: context.repo.repo, issue_number: context.issue.number });
            const bot = comments.find(c => c.user.type === 'Bot' && c.body.includes('ShipGate:'));
            if (bot) await github.rest.issues.updateComment({ owner: context.repo.owner, repo: context.repo.repo, comment_id: bot.id, body });
            else await github.rest.issues.createComment({ owner: context.repo.owner, repo: context.repo.repo, issue_number: context.issue.number, body });
