# @tier 3 — Auto-generated utility spec (export-only verification)
# exports: isAutoGeneratedSpec, hasAiRuleEvidence, findEmptyCategories, applyGuardrails, isIncompleteSpecCheck, formatGuardrailWarnings
# dependencies: 

domain Guardrails {
  version: "1.0.0"

  invariants exports_present {
    - true
  }
}
