/**
 * CI Workflow Generation
 *
 * Generates CI/CD workflow files for ShipGate verification.
 * Currently supports GitHub Actions. GitLab CI and CircleCI
 * can be added in the future.
 */

import type { ProjectProfile } from './detect.js';

// ─────────────────────────────────────────────────────────────────────────────
// GitHub Actions
// ─────────────────────────────────────────────────────────────────────────────

export interface WorkflowOptions {
  /** Source directories that trigger the workflow */
  srcPaths: string[];
  /** Node version to use (default: '20') */
  nodeVersion?: string;
  /** Fail-on level (default: 'error') */
  failOn?: string;
}

/**
 * Generate a GitHub Actions workflow for ShipGate verification.
 */
export function generateGitHubWorkflow(
  profile: ProjectProfile,
  options: WorkflowOptions = { srcPaths: ['src'] },
): string {
  const srcPaths = options.srcPaths.length > 0 ? options.srcPaths : ['src'];
  const nodeVersion = options.nodeVersion ?? '20';
  const failOn = options.failOn ?? 'error';

  const pathTriggers = [
    ...srcPaths.map((p) => `      - '${p}/**'`),
    "      - '**/*.isl'",
    "      - '.shipgate.yml'",
  ].join('\n');

  const installCmd = getInstallCommand(profile);

  return `# .github/workflows/shipgate.yml — Generated by shipgate init
# Docs: https://shipgate.dev/docs/ci
name: ShipGate ISL Verify

on:
  pull_request:
    paths:
${pathTriggers}

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '${nodeVersion}'

      - run: ${installCmd}

      - name: ShipGate Verify
        run: npx shipgate verify ${srcPaths.join(' ')} --fail-on ${failOn}
`;
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

function getInstallCommand(profile: ProjectProfile): string {
  switch (profile.packageManager) {
    case 'pnpm':
      return 'corepack enable && pnpm install --frozen-lockfile';
    case 'yarn':
      return 'yarn install --frozen-lockfile';
    case 'npm':
    default:
      return 'npm ci';
  }
}

/**
 * Get the path where the workflow file should be written.
 */
export function getWorkflowPath(profile: ProjectProfile): string | null {
  switch (profile.ciProvider) {
    case 'github':
      return '.github/workflows/shipgate.yml';
    default:
      // Default to GitHub Actions even if no CI detected
      return '.github/workflows/shipgate.yml';
  }
}
