import { describe, it, expect } from 'vitest';
import {
  parseTrailers,
  parseCoAuthors,
  extractAISignals,
  normalizeAgentName,
  parseCommitOutput,
} from './commit-parser.js';
import type { CommitMetadata } from './types.js';

describe('parseTrailers', () => {
  it('extracts trailers from commit body', () => {
    const body = 'Some commit message\n\nAI-Tool: cursor/claude-sonnet-4\nAI-Session: 2026-03-01T10:00:00Z';
    const trailers = parseTrailers(body);
    expect(trailers['ai-tool']).toBe('cursor/claude-sonnet-4');
    expect(trailers['ai-session']).toBe('2026-03-01T10:00:00Z');
  });

  it('excludes Co-authored-by from trailers', () => {
    const body = 'msg\n\nCo-authored-by: Copilot <noreply@github.com>\nAI-Tool: copilot';
    const trailers = parseTrailers(body);
    expect(trailers['co-authored-by']).toBeUndefined();
    expect(trailers['ai-tool']).toBe('copilot');
  });

  it('returns empty object for body without trailers', () => {
    expect(parseTrailers('just a message')).toEqual({});
  });

  it('stops parsing at non-trailer lines', () => {
    const body = 'paragraph text\n\nmore text\n\nAI-Tool: cursor';
    const trailers = parseTrailers(body);
    expect(trailers['ai-tool']).toBe('cursor');
  });
});

describe('parseCoAuthors', () => {
  it('extracts single Co-authored-by', () => {
    const body = 'msg\n\nCo-authored-by: GitHub Copilot <noreply@github.com>';
    const coAuthors = parseCoAuthors(body);
    expect(coAuthors).toHaveLength(1);
    expect(coAuthors[0]).toEqual({ name: 'GitHub Copilot', email: 'noreply@github.com' });
  });

  it('extracts multiple Co-authored-by entries', () => {
    const body = [
      'msg',
      '',
      'Co-authored-by: Claude <claude@anthropic.com>',
      'Co-authored-by: GitHub Copilot <noreply@github.com>',
    ].join('\n');
    const coAuthors = parseCoAuthors(body);
    expect(coAuthors).toHaveLength(2);
    expect(coAuthors[0]!.name).toBe('Claude');
    expect(coAuthors[1]!.name).toBe('GitHub Copilot');
  });

  it('returns empty for no co-authors', () => {
    expect(parseCoAuthors('just a message')).toEqual([]);
  });
});

describe('extractAISignals', () => {
  function makeMeta(overrides: Partial<CommitMetadata> = {}): CommitMetadata {
    return {
      hash: 'abc123',
      message: 'test commit',
      body: '',
      authorName: 'Test User',
      authorEmail: 'test@example.com',
      authorDate: '2026-03-01T10:00:00Z',
      trailers: {},
      coAuthors: [],
      ...overrides,
    };
  }

  it('detects AI-Tool trailer (highest confidence)', () => {
    const meta = makeMeta({ trailers: { 'ai-tool': 'cursor/claude-sonnet-4' } });
    const signals = extractAISignals(meta);
    expect(signals).toHaveLength(1);
    expect(signals[0]).toMatchObject({
      agent: 'cursor',
      model: 'claude-sonnet-4',
      confidence: 'high',
      method: 'commit-trailer',
    });
  });

  it('detects Co-authored-by: GitHub Copilot', () => {
    const meta = makeMeta({
      coAuthors: [{ name: 'GitHub Copilot', email: 'noreply@github.com' }],
    });
    const signals = extractAISignals(meta);
    expect(signals.length).toBeGreaterThanOrEqual(1);
    const copilotSignal = signals.find((s) => s.agent === 'copilot' && s.method === 'co-authored-by');
    expect(copilotSignal).toBeDefined();
    expect(copilotSignal!.confidence).toBe('high');
  });

  it('detects Co-authored-by: Claude', () => {
    const meta = makeMeta({
      coAuthors: [{ name: 'Claude', email: 'claude@anthropic.com' }],
    });
    const signals = extractAISignals(meta);
    const claudeSignal = signals.find((s) => s.agent === 'claude-code');
    expect(claudeSignal).toBeDefined();
  });

  it('detects [cursor] in commit message', () => {
    const meta = makeMeta({ message: '[cursor] add login form' });
    const signals = extractAISignals(meta);
    const cursorSignal = signals.find((s) => s.agent === 'cursor');
    expect(cursorSignal).toBeDefined();
    expect(cursorSignal!.confidence).toBe('medium');
    expect(cursorSignal!.method).toBe('commit-message');
  });

  it('detects "generated by copilot" in body', () => {
    const meta = makeMeta({ body: 'This code was generated by Copilot' });
    const signals = extractAISignals(meta);
    const signal = signals.find((s) => s.agent === 'copilot');
    expect(signal).toBeDefined();
  });

  it('detects aider: prefix', () => {
    const meta = makeMeta({ message: 'aider: refactor utils' });
    const signals = extractAISignals(meta);
    expect(signals.find((s) => s.agent === 'aider')).toBeDefined();
  });

  it('detects AI-Model trailer and infers agent', () => {
    const meta = makeMeta({ trailers: { 'ai-model': 'claude-3-opus' } });
    const signals = extractAISignals(meta);
    expect(signals[0]).toMatchObject({
      agent: 'claude-code',
      model: 'claude-3-opus',
      confidence: 'high',
    });
  });

  it('returns empty array for pure human commit', () => {
    const meta = makeMeta();
    const signals = extractAISignals(meta);
    expect(signals).toEqual([]);
  });

  it('sorts signals by confidence (high first)', () => {
    const meta = makeMeta({
      message: '[cursor] refactor',
      coAuthors: [{ name: 'Claude', email: 'claude@anthropic.com' }],
    });
    const signals = extractAISignals(meta);
    expect(signals.length).toBeGreaterThanOrEqual(2);
    expect(signals[0]!.confidence).toBe('high');
  });
});

describe('normalizeAgentName', () => {
  it.each([
    ['cursor', 'cursor'],
    ['Cursor', 'cursor'],
    ['copilot', 'copilot'],
    ['GitHub Copilot', 'copilot'],
    ['claude', 'claude-code'],
    ['claude-code', 'claude-code'],
    ['anthropic', 'claude-code'],
    ['codex', 'codex'],
    ['gemini', 'gemini'],
    ['windsurf', 'windsurf'],
    ['aider', 'aider'],
    ['cody', 'cody'],
    ['codeium', 'cody'],
    ['unknown-tool', 'unknown-ai'],
  ])('normalizes "%s" to "%s"', (input, expected) => {
    expect(normalizeAgentName(input)).toBe(expected);
  });
});

describe('parseCommitOutput', () => {
  it('parses structured git log output', () => {
    const raw = [
      'abc123def456',
      'feat: add login',
      'This adds the login flow',
      '',
      'AI-Tool: cursor/claude-sonnet-4',
      '---AUTHOR---',
      'John Doe',
      'john@example.com',
      '2026-03-01T10:00:00+00:00',
      '---END---',
    ].join('\n');

    const meta = parseCommitOutput(raw, 'abc123');
    expect(meta.hash).toBe('abc123def456');
    expect(meta.message).toBe('feat: add login');
    expect(meta.authorName).toBe('John Doe');
    expect(meta.authorEmail).toBe('john@example.com');
    expect(meta.trailers['ai-tool']).toBe('cursor/claude-sonnet-4');
  });
});
