import Link from "next/link";
import { ArrowRight, Bot, GitBranch, BookOpen } from "lucide-react";

export const metadata = {
  title: "Guides",
  description: "Practical guides for using ISL effectively.",
};

const guides = [
  {
    icon: Bot,
    title: "Validating AI Code",
    href: "/docs/guides/validating-ai-code",
    description: "Use ISL to verify code generated by Cursor, Copilot, Claude, and other AI tools.",
    time: "10 min read",
  },
  {
    icon: GitBranch,
    title: "CI/CD Integration",
    href: "/docs/guides/ci-cd-integration",
    description: "Add ISL checks to your CI/CD pipelines for automated verification.",
    time: "8 min read",
  },
  {
    icon: BookOpen,
    title: "Writing Good Specs",
    href: "/docs/guides/writing-good-specs",
    description: "Best practices for writing clear, maintainable ISL specifications.",
    time: "12 min read",
  },
];

export default function GuidesPage() {
  return (
    <div>
      <h1>Guides</h1>
      <p className="lead text-xl text-muted-foreground mb-8">
        Practical guides for using ISL effectively in your projects.
      </p>

      <div className="not-prose grid gap-6">
        {guides.map((guide) => (
          <Link
            key={guide.href}
            href={guide.href}
            className="group flex items-start gap-4 p-6 rounded-xl border border-border bg-card hover:border-primary/50 transition-all"
          >
            <div className="w-12 h-12 rounded-lg bg-primary/10 flex items-center justify-center shrink-0 group-hover:bg-primary/20 transition-colors">
              <guide.icon className="w-6 h-6 text-primary" />
            </div>
            <div className="flex-1 min-w-0">
              <div className="flex items-center gap-2 mb-1">
                <h2 className="text-lg font-semibold group-hover:text-primary transition-colors">
                  {guide.title}
                </h2>
                <ArrowRight className="w-4 h-4 opacity-0 -translate-x-2 group-hover:opacity-100 group-hover:translate-x-0 transition-all text-primary" />
              </div>
              <p className="text-muted-foreground mb-2">{guide.description}</p>
              <span className="text-xs text-muted-foreground">{guide.time}</span>
            </div>
          </Link>
        ))}
      </div>
    </div>
  );
}
