import type {
  WorkflowRun,
  PullRequest,
  Environment,
  Finding,
  TeamMember,
  TimelineEvent,
  Webhook,
  SummaryCard,
} from './types';

export const workflowRuns: WorkflowRun[] = [
  {
    id: '1',
    name: 'ShipGate Verify',
    event: 'pull_request',
    branch: 'feat/payment-flow',
    status: 'success',
    duration: '1m 23s',
    time: '3m ago',
    pr: '#142',
    author: 'gee',
    commit: 'a1b2c3d',
    commitMsg: 'feat: add Stripe webhook handler',
    jobs: [
      { name: 'Install', status: 'success', duration: '12s' },
      { name: 'shipgate verify', status: 'success', duration: '28s' },
      { name: 'shipgate ship --ci', status: 'success', duration: '34s' },
      { name: 'Post PR Comment', status: 'success', duration: '3s' },
      { name: 'Upload SARIF', status: 'success', duration: '6s' },
    ],
    verdict: 'SHIP',
    score: 94,
  },
  {
    id: '2',
    name: 'ShipGate Verify',
    event: 'pull_request',
    branch: 'fix/auth-middleware',
    status: 'running',
    duration: '0m 42s',
    time: 'now',
    pr: '#143',
    author: 'alex',
    commit: 'd4e5f6g',
    commitMsg: 'fix: validate JWT expiry',
    jobs: [
      { name: 'Install', status: 'success', duration: '11s' },
      { name: 'shipgate verify', status: 'running', duration: '31s' },
      { name: 'shipgate ship --ci', status: 'pending', duration: '—' },
      { name: 'Post PR Comment', status: 'pending', duration: '—' },
      { name: 'Upload SARIF', status: 'pending', duration: '—' },
    ],
    verdict: null,
    score: null,
  },
  {
    id: '3',
    name: 'ShipGate Verify',
    event: 'pull_request',
    branch: 'feat/email-service',
    status: 'failure',
    duration: '1m 08s',
    time: '1h ago',
    pr: '#139',
    author: 'sam',
    commit: 'h7i8j9k',
    commitMsg: 'feat: email templates with AI',
    jobs: [
      { name: 'Install', status: 'success', duration: '13s' },
      { name: 'shipgate verify', status: 'success', duration: '26s' },
      { name: 'shipgate ship --ci', status: 'failure', duration: '22s' },
      { name: 'Post PR Comment', status: 'success', duration: '4s' },
      { name: 'Upload SARIF', status: 'success', duration: '5s' },
    ],
    verdict: 'NO_SHIP',
    score: 41,
    blockers: [
      '2 hardcoded secrets detected',
      '3 hallucinated imports',
      'Auth missing on /api/email/send',
    ],
  },
];

export const pullRequests: PullRequest[] = [
  {
    number: 142,
    title: 'feat: add Stripe webhook handler',
    author: 'gee',
    branch: 'feat/payment-flow',
    verdict: 'SHIP',
    score: 94,
    filesChanged: 8,
    opened: '2h ago',
    checks: [
      { name: 'ShipGate Verify', status: 'pass' },
      { name: 'TypeScript', status: 'pass' },
      { name: 'Tests', status: 'pass' },
      { name: 'Lint', status: 'pass' },
    ],
  },
  {
    number: 143,
    title: 'fix: validate JWT expiry in auth middleware',
    author: 'alex',
    branch: 'fix/auth-middleware',
    verdict: null,
    score: null,
    filesChanged: 3,
    opened: '15m ago',
    checks: [
      { name: 'ShipGate Verify', status: 'running' },
      { name: 'TypeScript', status: 'pass' },
      { name: 'Tests', status: 'running' },
      { name: 'Lint', status: 'pass' },
    ],
  },
  {
    number: 139,
    title: 'feat: email templates with AI generation',
    author: 'sam',
    branch: 'feat/email-service',
    verdict: 'NO_SHIP',
    score: 41,
    filesChanged: 12,
    opened: '1d ago',
    checks: [
      { name: 'ShipGate Verify', status: 'fail' },
      { name: 'TypeScript', status: 'pass' },
      { name: 'Tests', status: 'fail' },
      { name: 'Lint', status: 'pass' },
    ],
  },
];

export const environments: Environment[] = [
  {
    name: 'Production',
    url: 'app.acme.com',
    status: 'protected',
    lastDeploy: {
      commit: 'f9e8d7c',
      verdict: 'SHIP',
      score: 96,
      time: '2d ago',
      author: 'gee',
    },
    rules: [
      'Requires SHIP verdict',
      'Score ≥ 90',
      '0 critical findings',
      'SOC 2 ≥ 80%',
    ],
    history: [96, 94, 92, 95, 93, 96],
  },
  {
    name: 'Staging',
    url: 'staging.acme.com',
    status: 'gated',
    lastDeploy: {
      commit: 'a1b2c3d',
      verdict: 'SHIP',
      score: 94,
      time: '3m ago',
      author: 'gee',
    },
    rules: ['Requires SHIP or WARN', 'Score ≥ 70'],
    history: [82, 85, 88, 91, 93, 94],
  },
  {
    name: 'Preview',
    url: 'pr-142.acme.com',
    status: 'open',
    lastDeploy: {
      commit: 'a1b2c3d',
      verdict: 'WARN',
      score: 73,
      time: '15m ago',
      author: 'alex',
    },
    rules: ['Any verdict allowed'],
    history: [60, 62, 65, 68, 70, 73],
  },
];

export const findings: Finding[] = [
  {
    id: '1',
    severity: 'critical',
    engine: 'Secret Scanner',
    message: 'Hardcoded Stripe key in emailService.ts:24',
    file: 'emailService.ts',
    line: 24,
    pr: '#139',
    fixable: true,
  },
  {
    id: '2',
    severity: 'critical',
    engine: 'Hallucination',
    message: "Package 'sendgrid-v4-next' does not exist on npm",
    file: 'emailService.ts',
    line: 1,
    pr: '#139',
    fixable: true,
  },
  {
    id: '3',
    severity: 'high',
    engine: 'Hallucination',
    message: 'Route /api/email/verify has no handler',
    file: 'emailRouter.ts',
    line: 18,
    pr: '#139',
    fixable: false,
  },
  {
    id: '4',
    severity: 'medium',
    engine: 'Type Safety',
    message: "Implicit 'any' on webhookPayload parameter",
    file: 'webhookHandler.ts',
    line: 42,
    pr: '#142',
    fixable: true,
  },
  {
    id: '5',
    severity: 'medium',
    engine: 'Error Handling',
    message: 'Missing try/catch in async route handler',
    file: 'paymentRouter.ts',
    line: 67,
    pr: '#142',
    fixable: true,
  },
  {
    id: '6',
    severity: 'low',
    engine: 'Console',
    message: 'console.log left in production code',
    file: 'authService.ts',
    line: 33,
    pr: '#142',
    fixable: true,
  },
];

export const teamMembers: TeamMember[] = [
  {
    name: 'Gee',
    role: 'Lead',
    scans: 142,
    shipRate: 94,
    topIssue: 'Type safety',
    avatar: 'G',
    streak: 12,
  },
  {
    name: 'Alex',
    role: 'Backend',
    scans: 89,
    shipRate: 87,
    topIssue: 'Error handling',
    avatar: 'A',
    streak: 7,
  },
  {
    name: 'Sam',
    role: 'Full-stack',
    scans: 67,
    shipRate: 71,
    topIssue: 'AI hallucinations',
    avatar: 'S',
    streak: 3,
  },
];

export const timelineEvents: TimelineEvent[] = [
  {
    id: '1',
    time: '3m ago',
    type: 'ship',
    message: 'PR #142 passed — SHIP (94)',
    detail: 'feat: add Stripe webhook handler',
    author: 'gee',
  },
  {
    id: '2',
    time: '15m ago',
    type: 'running',
    message: 'PR #143 scanning...',
    detail: 'fix: validate JWT expiry',
    author: 'alex',
  },
  {
    id: '3',
    time: '47m ago',
    type: 'deploy',
    message: 'Deployed to staging',
    detail: 'commit a1b2c3d → staging.acme.com',
    author: 'gee',
  },
  {
    id: '4',
    time: '1h ago',
    type: 'noship',
    message: 'PR #139 blocked — NO_SHIP (41)',
    detail: 'feat: email templates with AI',
    author: 'sam',
  },
  {
    id: '5',
    time: '2h ago',
    type: 'fix',
    message: '3 issues auto-fixed in PR #138',
    detail: 'Removed console.logs, added error boundaries',
    author: 'system',
  },
  {
    id: '6',
    time: '3h ago',
    type: 'alert',
    message: 'SOC 2 coverage dropped below 80%',
    detail: 'CC7.1 Vulnerability Management → PARTIAL',
    author: 'system',
  },
  {
    id: '7',
    time: '1d ago',
    type: 'deploy',
    message: 'Deployed to production',
    detail: 'commit f9e8d7c → app.acme.com (score: 96)',
    author: 'gee',
  },
];

export const webhooks: Webhook[] = [
  {
    id: '1',
    event: 'verify.complete',
    url: 'https://hooks.slack.com/...',
    status: 'active',
    lastFired: '3m ago',
  },
  {
    id: '2',
    event: 'verdict.noship',
    url: 'https://hooks.slack.com/...',
    status: 'active',
    lastFired: '1h ago',
  },
  {
    id: '3',
    event: 'compliance.drop',
    url: 'https://api.pagerduty.com/...',
    status: 'active',
    lastFired: '3h ago',
  },
  {
    id: '4',
    event: 'deploy.blocked',
    url: 'https://api.opsgenie.com/...',
    status: 'paused',
    lastFired: '2d ago',
  },
];

export const summaryCards: SummaryCard[] = [
  { label: 'Open PRs', value: '3', sub: '1 scanning', color: '#6366f1', icon: '↗' },
  { label: 'Pipeline', value: '2/3', sub: 'pass rate', color: '#00e68a', icon: '◎' },
  { label: 'Deploys Today', value: '2', sub: 'staging + preview', color: '#38bdf8', icon: '▲' },
  { label: 'Active Findings', value: '6', sub: '2 critical', color: '#ff5c6a', icon: '!' },
  { label: 'Ship Rate', value: '86%', sub: '7d rolling', color: '#00e68a', icon: '✓' },
  { label: 'SOC 2', value: '83%', sub: '7/7 controls', color: '#00e68a', icon: '🛡' },
];
